# Generated by Django 4.1.2 on 2022-10-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=80)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=15)),
                ('long', models.DecimalField(decimal_places=5, max_digits=15)),
                ('asosiasi', models.CharField(max_length=20)),
            ],
        ),
    ]
