# Generated by Django 4.1.2 on 2022-11-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superhero',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='long',
        ),
    ]
