# Generated by Django 4.1.2 on 2022-11-03 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peta', '0002_remove_superhero_lat_remove_superhero_long'),
        ('batasdesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunanpogung',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peta.superhero'),
        ),
    ]
